site_name: MatrixOne Cloud 文档
theme:
  name: material
  logo: assets/new-logo.png
  features:
    - content.code.copy
    - content.action.edit
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
  palette:
    scheme: mo
  font:
    text: Ubuntu
repo_url: https://github.com/matrixone-cloud/moc-docs
edit_uri: edit/main/docs/
extra:
  homepage: https://www.matrixorigin.cn/MatrixOneCloud
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - MatrixOne-Cloud:
    - 主页: README.md
    - 关于 MatrixOne Cloud:
      - MatrixOne Cloud 简介: MatrixOne-Cloud/Overview/matrixonecloud-introduction.md
      - MySQL 兼容性: MatrixOne-Cloud/Overview/mysql-compatibility.md
    - 快速开始:
      - 快速创建 MatrixOne Cloud（MO Cloud）实例: MatrixOne-Cloud/Get-Started/quickstart.md
    - 应用开发:
      - 连接到 MatrixOne:
        - 客户端工具连接: MatrixOne-Cloud/App-Develop/connect-mo/database-client-tools.md
        - 使用 Web 页面连接: MatrixOne-Cloud/App-Develop/connect-mo/connect-mo-with-web.md
        - Java 连接:
          - JDBC 连接: MatrixOne-Cloud/App-Develop/connect-mo/java-connect-to-matrixone/connect-mo-with-jdbc.md
          - Java ORMs 连接: MatrixOne-Cloud/App-Develop/connect-mo/java-connect-to-matrixone/connect-mo-with-orm.md
        - Python 连接: MatrixOne-Cloud/App-Develop/connect-mo/python-connect-to-matrixone.md
        - Golang 连接: MatrixOne-Cloud/App-Develop/connect-mo/connect-to-matrixone-with-go.md
      - 数据写入:
        - INSERT 插入: MatrixOne-Cloud/App-Develop/insert-data.md
      - 数据读取:
        - 单表读取: MatrixOne-Cloud/App-Develop/read-data/query-data-single-table.md
        - 多表连接查询: MatrixOne-Cloud/App-Develop/read-data/multitable-join-query.md
        - 子查询: MatrixOne-Cloud/App-Develop/read-data/subquery.md
        - 视图: MatrixOne-Cloud/App-Develop/read-data/views.md
        - 公共表表达式: MatrixOne-Cloud/App-Develop/read-data/cte.md
      - 应用开发示例:
        - Java 基础示例: MatrixOne-Cloud/App-Develop/Tutorial/develop-java-crud-demo.md
        - SpringBoot 和 JPA 基础示例: MatrixOne-Cloud/App-Develop/Tutorial/springboot-hibernate-crud-demo.md
        - SpringBoot 和 MyBatis 基础示例: MatrixOne-Cloud/App-Develop/Tutorial/springboot-mybatis-crud-demo.md
        - Python 基础示例: MatrixOne-Cloud/App-Develop/Tutorial/develop-python-crud-demo.md
        - SQLAlchemy 基础示例: MatrixOne-Cloud/App-Develop/Tutorial/sqlalchemy-python-crud-demo.md
        - Golang 基础示例: MatrixOne-Cloud/App-Develop/Tutorial/develop-golang-crud-demo.md
        - Gorm 基础示例: MatrixOne-Cloud/App-Develop/Tutorial/gorm-golang-crud-demo.md
    - 管理实例:
      - 创建实例: MatrixOne-Cloud/Instance-Mgmt/create-instance.md
      - 连接实例: MatrixOne-Cloud/Instance-Mgmt/connect-instance.md
      - 终止和恢复实例: MatrixOne-Cloud/Instance-Mgmt/terminate-recovery-instance.md
